---
- name: Install required packages
  apt:
    update_cache: yes
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present