---
- name: Install Nginx
  apt:
    name: nginx
#- name: Nginx web server configuration
#  ansible.builtin.template:
#    src: nginx.conf.j2
#    dest: /etc/nginx/nginx.conf
#    owner: root
#    group: root
#    mode: '0644'
#    state: present
- name: Nginx default page config
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  notify: "restart web services"
- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
- name: Install Docker
  apt:
    name: docker-ce
    state: latest