---
- name: Install Nginx
  apt:
    name: nginx
    state: present
- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
- name: Install Docker
  apt:
    name: docker-ce
    state: latest