---
- name: Create SSH key and Droplet
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - ../vars/do.yml

  tasks:
    - name: provision ssh key
      digitalocean.cloud.ssh_key:
        state: present
        token: "{{ digitalocean_token }}"
        public_key: "{{ public_key }}"
        name: "juke-{{ env }}"
      register: ssh_key

    - name: provision web servers
      digitalocean.cloud.droplet:
        state: present
        token: "{{ digitalocean_token }}"
        name: "juke-web-{{ item }}"
        region: nyc3
        size: s-1vcpu-2gb
        image: ubuntu-22-04-x64
        ssh_keys: ["{{ ssh_key.ssh_key.id }}"]
        unique_name: true
        tags:
          - webservers
      with_sequence: start=1 end="{{ desired_number_of_webservers }}"

#    - name: provision varnish cache server
#      digitalocean.cloud.droplet:
#        state: present
#        token: "{{ digitalocean_token }}"
#        name: juke-web-cache
#        region: nyc3
#        size: s-1vcpu-2gb
#        image: ubuntu-22-04-x64
#        ssh_keys: ["{{ ssh_key.ssh_key.id }}"]
#        unique_name: true
#        tags:
#          - varnish

    - name: provision load balancer
      digitalocean.cloud.droplet:
        state: present
        token: "{{ digitalocean_token }}"
        name: juke-web-lb
        region: nyc3
        size: s-1vcpu-2gb
        image: ubuntu-22-04-x64
        ssh_keys: ["{{ ssh_key.ssh_key.id }}"]
        unique_name: true
        tags:
          - loadbalancers
